# Generated by Django 3.1.2 on 2020-12-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazyhelper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
